In [ ]:
import numpy as np
from scipy.spatial.transform import Rotation as scir

camera_pose = np.array([
        [
            -0.08712875843048096,
            0.9843230247497559,
            0.15335312485694885,
            0.3282797038555145
        ],
        [
            0.9961972236633301,
            0.0860944390296936,
            0.01338338851928711,
            0.0723816379904747
        ],
        [
            -2.928823232650757e-05,
            0.1539360135793686,
            -0.9880810976028442,
            1.5728518962860107
        ],
        [
            0.0,
            0.0,
            0.0,
            1.0
        ]
    ])

print(camera_pose)

C = np.array([
    [0,  1, 0, 0],
    [-1, 0, 0, 0],
    [0,  0, 1, 0],
    [0,  0, 0, 1],
        ], dtype=float)
camera_pose = C @ camera_pose 
print(camera_pose)

delta_x_left = 1
delta_y_left = 0
delta_z_left = 0

translation_left = np.array([delta_x_left, delta_y_left, delta_z_left])
magnitude_left = np.linalg.norm(translation_left) # 记录magnitude如果有其他地方用到

transformation_left = np.eye(4)
transformation_left[:3, 3] = translation_left


x_euler_left = 0
y_euler_left = 0
z_euler_left = 0

rot_euler_left = np.array([x_euler_left, y_euler_left, z_euler_left])
rot_left = scir.from_euler('xyz', rot_euler_left, degrees=True).as_matrix()
transformation_left[:3,:3] = rot_left  
                    
transformation_left = np.matmul(transformation_left, pre_conversion)




local_transform = np.linalg.inv(camera_pose) @ world_transform @ camera_pose
local_delta_xyz = local_transform[:3, 3]
local_euler_xyz = scir.from_matrix(local_transform[:3, :3]).as_euler('xyz', degrees=True)

print(local_delta_xyz)
print(local_euler_xyz)

[[-8.71287584e-02  9.84323025e-01  1.53353125e-01  3.28279704e-01]
 [ 9.96197224e-01  8.60944390e-02  1.33833885e-02  7.23816380e-02]
 [-2.92882323e-05  1.53936014e-01 -9.88081098e-01  1.57285190e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[ 9.96197224e-01  8.60944390e-02  1.33833885e-02  7.23816380e-02]
 [ 8.71287584e-02 -9.84323025e-01 -1.53353125e-01 -3.28279704e-01]
 [-2.92882323e-05  1.53936014e-01 -9.88081098e-01  1.57285190e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]


AttributeError: module 'scipy.spatial.transform' has no attribute 'from_euler'

In [19]:
import pickle

path = "/home/zsh/dcoda/RLBench/tools/data/rlbench_data/coordinated_lift_ball/all_variations/episodes/episode2/low_dim_obs.pkl"

with open(path, "rb") as f:
    data = pickle.load(f)

print(data[0].misc['wrist_left_camera_intrinsics'])

[[-110.85124795    0.           64.        ]
 [   0.         -110.85124795   64.        ]
 [   0.            0.            1.        ]]
